name: Lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js and setup npm cache
        uses: ./.github/actions/node-and-npm-cache
      - name: Lint
        run: |
          npm ci
          npm run lint
